import fs from 'fs';

const args = process.argv.slice(2);
const into = args[0] === '--into' ? args.splice(0, 2)[1] : null;
if (!args.length) { console.log('usage: node table.mjs [--into file.md] scan1.json scan2.json ...'); process.exit(1); }
const q = (arr, p) => { const a = arr.filter(v => v === v).sort((x, y) => x - y); return a.length ? a[Math.min(a.length - 1, Math.floor(p * (a.length - 1) + 0.5))] : '-'; };
const sum = (a, k) => a.pct.slice(...k).reduce((t, v) => t + v, 0).toFixed(1);
const rows = [];
for (const f of args) {
  const a = JSON.parse(fs.readFileSync(f, 'utf8'));
  const h = a.hills, b = a.bowls;
  const tops = Object.entries(a.paint).sort((x, y) => y[1].share - x[1].share).slice(0, 4).map(([k, v]) => `${k} ${v.share}`).join(', ');
  rows.push([
    a.name, `${a.grid.S}`, `${a.height.p10}/${a.height.p50}/${a.height.p90}`, `${a.relief100.p50}/${a.relief100.p90}`,
    `${sum(a.slope, [0, 1])}/${sum(a.slope, [1, 3])}/${sum(a.slope, [3, 5])}/${sum(a.slope, [5, 7])}/${sum(a.slope, [7])}`,
    `${a.bump}`, `${a.steepPatches ? a.steepPatches.n : '-'}`, `${a.kinks ? a.kinks.n : '-'}`, `${a.reach ? a.reach.pct : '-'}`,
    h.length ? `${h.length}: h ${q(h.map(x => x.h), 0.5)}, r ${q(h.map(x => x.r), 0.5)}, r/h ${q(h.map(x => x.rOverH), 0.5)}, worst ${q(h.map(x => x.climbWorst), 0.5)}/${q(h.map(x => x.climbWorst), 0.9)}, ok ${h.filter(x => x.climbOk === x.rays).length}` : '0',
    b.length ? `${b.length}: d ${q(b.map(x => x.h), 0.5)}, r ${q(b.map(x => x.r), 0.5)}, r/d ${q(b.map(x => x.rOverH), 0.5)}, wall ${q(b.map(x => x.climbWorst), 0.5)}/${q(b.map(x => x.climbWorst), 0.9)}, ok ${b.filter(x => x.climbOk === x.rays).length}` : '0',
    a.path.pieces ? `${a.path.wP25}/${a.path.wP50}/${a.path.wP90}` : '-', `${a.blade}/${a.pay}`, `${a.specks}`, tops,
  ]);
}
const head = ['scan', 'step', 'height p10/50/90', 'relief/100 p50/p90', 'slope % <3/3-13/13-25/25-35/>35', 'bump', 'steep patches', 'crease patches', 'reachable %', 'hills (medians; worst p50/p90; all rays <=25)', 'bowls (medians; wall p50/p90; all exits <=25)', 'path width p25/50/90', 'blade/pay %', 'specks', 'top paints %'];
const md = [
  `Generated by scripts/analyze/table.mjs from ${args.map(f => f.replace(/^.*[\\/]/, '')).join(', ')} on ${new Date().toISOString().slice(0, 16)}Z. Do not edit by hand: rerun \`run.sh analyze\` + table.mjs. Definitions: the \`defs\` block in each JSON.`,
  '',
  '| ' + head.join(' | ') + ' |',
  '|' + head.map(() => '---').join('|') + '|',
  ...rows.map(r => '| ' + r.join(' | ') + ' |'),
].join('\n');
if (into) {
  const s = fs.readFileSync(into, 'utf8');
  const a = s.indexOf('<!-- measured:begin -->'), b = s.indexOf('<!-- measured:end -->');
  if (a < 0 || b < 0) throw new Error(`${into}: missing <!-- measured:begin --> / <!-- measured:end --> markers`);
  fs.writeFileSync(into, s.slice(0, a + 23) + '\n' + md + '\n' + s.slice(b));
  console.log(`wrote ${rows.length} rows into ${into}`);
} else console.log(md);
